spring.application.name=Projetofinal

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=3011

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

