spring.application.name=Projetofinal

spring.datasource.url=jdbc:postgresql://junction.proxy.rlwy.net:16926/railway
spring.datasource.username=postgres
spring.datasource.password=qoMspUdKSWFTVWwQEEhwfqOAXlpwOsXE

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
